site_name: React Auth Kit
site_description: Powerful and easy to use authentication management Library for React JS apps, uses Token-Based Authentication using JSON Web Token
site_author: Arkadip Bhattacharya
site_url: https://authkit.arkadip.dev/

repo_url: https://github.com/react-auth-kit/react-auth-kit
repo_name: react-auth-kit/react-auth-kit

copyright:  Copyright &copy; 2020 - 2023 React Auth Kit

theme:
  name: 'material'
  custom_dir: docs/docs_overrides/
  icon:
    repo: fontawesome/brands/github
  logo: img/logo.svg
  favicon: img/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - navigation.top
    - navigation.sections
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow


nav:
  - Home: 'index.md'

  - Getting Started:
    - 'getting_started/index.md'
    - Installation: 'getting_started/installation.md'
    - Integration: 'getting_started/integration.md'
    - Execute User Sign In: 'getting_started/signin.md'
    - Execute User Sign Out: 'getting_started/signout.md'
    - Private Route: 'getting_started/privateroute.md'
    - Get User's Data: 'getting_started/authdata.md'
    - Get Auth Header for Network request: 'getting_started/authheader.md'
    - Check the Authentication Status: 'getting_started/checkauth.md'
    - Refresh Token: 'getting_started/refreshtoken.md'

  - Reference: 
    - 'reference/index.md'
    - React Auth Kit:
      - AuthProvider: 'reference/react-auth-kit/authprovider.md'
      - createRefresh: 'reference/react-auth-kit/createRefresh.md'
      - createStore: 'reference/react-auth-kit/createStore.md'
      - Errors: 'reference/react-auth-kit/errors.md'
      - Hooks:
        - 'reference/react-auth-kit/hooks/index.md'
        - useAuthHeader: 'reference/react-auth-kit/hooks/useAuthHeader.md'
        - useAuthUser: 'reference/react-auth-kit/hooks/useAuthUser.md'
        - useIsAuthenticated: 'reference/react-auth-kit/hooks/useIsAuthenticated.md'
        - useSignIn: 'reference/react-auth-kit/hooks/useSignIn.md'
        - useSignOut: 'reference/react-auth-kit/hooks/useSignOut.md'
      - Higher Order Component:
        - 'reference/react-auth-kit/hoc/index.md'
        - useAuthHeader: 'reference/react-auth-kit/hoc/withAuthHeader.md'
        - withAuthuser: 'reference/react-auth-kit/hoc/withAuthUser.md'
        - withIsAuthenticated: 'reference/react-auth-kit/hoc/withIsAuthenticated.md'
        - withSignIn: 'reference/react-auth-kit/hoc/withSignIn.md'
        - withSignOut: 'reference/react-auth-kit/hoc/withSignOut.md'
    - '@auth-kit/react-router':
      - RequireAuth: 'reference/react-router/requireauth.md'
      - AuthOutlet: 'reference/react-router/authoutlet.md'

  - Upgradation Guide:
      - 'update/index.md'
      - Update from v2 to v3: 'update/2to3.md'
      - Update from v1 to v2: 'update/1to2.md'

  - Contributing: 'contributing.md'

extra:
  analytics:
    provider: google
    property: G-G1WZBFV5R2
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

plugins:
  - search

extra_javascript:
  - https://media.ethicalads.io/media/client/ethicalads.min.js

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
